---
- name: Check if {{ vault_hsm_token_label }} has been generated
  ansible.builtin.shell:
    cmd: "softhsm2-util --show-slots | grep -q {{ vault_hsm_token_label }}"
  changed_when: false
  register: hsm_check_token
  failed_when: hsm_check_token.rc not in [0, 1]

- name: Generate HSM key for Vault instance
  ansible.builtin.shell:
    cmd: >-
      softhsm2-util --init-token --free
      --label {{ vault_hsm_token_label }}
      --pin {{ vault_hsm_pin }}
      --so-pin {{ vault_hsm_so_pin }}
  changed_when: true
  when: hsm_check_token.rc != 0

- name: Get {{ vault_hsm_token_label }} slot
  ansible.builtin.shell:
    cmd: >-
      softhsm2-util --show-slots | grep -B15 {{ vault_hsm_token_label }} |
      grep ^Slot | sed 'q;d' | cut -d\  -f2
  changed_when: false
  register: hsm_vault_slot

- name: Set the slot fact for Vault HSM
  ansible.builtin.set_fact:
    vault_hsm_token_slot: "{{ hsm_vault_slot.stdout }}"
