---
- name: Create vault hsm token directory
  become: true
  ansible.builtin.file:
    dest: "{{ vault_softhsm_token_dir }}"
    owner: "{{ vault_hsm_user }}"
    group: "{{ vault_hsm_group }}"
    mode: '0755'
    state: directory

- name: Configure softhsm2 config
  become: true
  ansible.builtin.template:
    src: softhsm2.conf.j2
    dest: "{{ vault_softhsm_config_path }}"
    owner: "{{ vault_hsm_user }}"
    group: "{{ vault_hsm_group }}"
    mode: '0644'

- name: Check if {{ vault_hsm_token_label }} has been generated
  ansible.builtin.shell:
    cmd: "softhsm2-util --show-slots | grep -q {{ vault_hsm_token_label }}"
  changed_when: false
  register: hsm_check_token
  failed_when: hsm_check_token.rc not in [0, 1]

- name: Generate HSM key for Vault instance
  become: true
  become_user: "{{ vault_hsm_user }}"
  ansible.builtin.shell:
    cmd: >-
      softhsm2-util --init-token --free
      --label {{ vault_hsm_token_label }}
      --pin {{ vault_hsm_pin }}
      --so-pin {{ vault_hsm_so_pin }}
  changed_when: true
  when: hsm_check_token.rc != 0

- name: Get {{ vault_hsm_token_label }} slot
  ansible.builtin.shell:
    cmd: >-
      softhsm2-util --show-slots | grep -B15 {{ vault_hsm_token_label }} |
      grep ^Slot | sed 'q;d' | cut -d\  -f2
  changed_when: false
  register: hsm_vault_slot

- name: Set the slot fact for Vault HSM
  ansible.builtin.set_fact:
    vault_hsm_token_slot: "{{ hsm_vault_slot.stdout }}"
    cacheable: true
