---
# https://wiki.opendnssec.org/display/SoftHSMDOCS/SoftHSM+Documentation+v2

# dnf module provides softhsm
# Module   : idm:DL1:8070020221109205654:93c20af6:x86_64
- name: Add idm:DL1 module
  become: true
  ansible.builtin.copy:
    dest: /etc/dnf/modules.d/idm.module
    content: |
      [idm]
      name=idm
      stream=DL1
      profiles=
      state=enabled
    owner: root
    group: root
    mode: '0644'

- name: Install dependencies
  become: true
  ansible.builtin.dnf:
    name:
      - libtool-ltdl-devel
      - opensc
    state: present

- name: Install SoftHSMv2
  become: true
  ansible.builtin.dnf:
    name: "{{ vault_hsm_package }}"
    update_cache: true
    state: present

- name: Set libsofthsm2 path fact
  ansible.builtin.set_fact:
    vault_hsm_lib_path: /lib64/softhsm/libsofthsm.so
    cacheable: true
