---
# https://wiki.opendnssec.org/display/SoftHSMDOCS/SoftHSM+Documentation+v2
- name: Install dependencies
  become: true
  ansible.builtin.yum:
    name:
      - libtool-ltdl-devel
      - opensc
    state: present

- name: Install SoftHSMv2
  become: true
  ansible.builtin.yum:
    name: "{{ vault_hsm_package }}"
    state: present
