---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: redhat8-vault-1
    image: almalinux:8
    dockerfile: ../common/Dockerfile.j2
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    capabilities:
      - CAP_SYS_ADMIN
      - CAP_IPC_LOCK
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      container: docker
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
verifier:
  name: ansible
