---
- name: Ensure Raft backend {{ vault_raft_path }} path is created
  become: true
  ansible.builtin.file:
    path: "{{ vault_raft_path }}"
    owner: vault
    group: vault
    state: directory
    mode: '0700'

- name: Populate Vault config.hcl
  become: true
  ansible.builtin.template:
    src: config.hcl.j2
    dest: "{{ vault_config_path }}"
    owner: vault
    group: vault
    mode: '0644'

- name: Configure Vault systemd service
  become: true
  ansible.builtin.template:
    src: vault.service.j2
    dest: "{{ vault_systemd_path }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd deamons
    - Restart Vault systemd service
