---
- name: Install HashiCorp Vault for RHEL7/8
  ansible.builtin.include_tasks: install-redhat7.yml
  when:
  - ansible_facts['os_family'] == "RedHat"
  - ansible_facts['distribution_major_version'] in ["7", "8"]
  tags: installation

- name: Update HashiCorp Vault config
  ansible.builtin.include_tasks: configure.yml
  tags: configuration

- name: Harden HashiCorp Vault
  ansible.builtin.include_tasks: hardening.yml
  tags: hardening
