---
- name: Converge
  hosts: all
  vars:
    vault_version: vault-1.12.0-1
    vault_raft_members:
      - ip: "{{ hostvars['vault-1']['ansible_default_ipv4']['address'] }}"
        port: 8200
  tasks:
    - name: Start the convergence playbook
      ansible.builtin.include_tasks: ../common/converge.yml
