---
- name: Converge
  hosts: all
  vars:
    vault_version: vault-1.12.0-1
    vault_raft_members:
      - ip: "{{ hostvars['vault-1']['ansible_default_ipv4']['address'] }}"
        port: 8200
      - ip: "{{ hostvars['vault-2']['ansible_default_ipv4']['address'] }}"
        port: 8200
      - ip: "{{ hostvars['vault-3']['ansible_default_ipv4']['address'] }}"
        port: 8200
  tasks:
    - name: "Install vault"
      ansible.builtin.include_role:
        name: "install_vault"
    - name: Start Vault systemd service
      become: true
      ansible.builtin.systemd:
        name: vault
        enabled: true
        state: started
