---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vault-1
    image: quay.io/centos/centos:centos7
    command: /sbin/init
    privileged: true
    capabilities:
      - CAP_SYS_ADMIN
      - CAP_IPC_LOCK
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      container: docker
  - name: vault-2
    image: quay.io/centos/centos:centos7
    command: /sbin/init
    privileged: true
    capabilities:
      - CAP_SYS_ADMIN
      - CAP_IPC_LOCK
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      container: docker
  - name: vault-3
    image: quay.io/centos/centos:centos7
    command: /sbin/init
    privileged: true
    capabilities:
      - CAP_SYS_ADMIN
      - CAP_IPC_LOCK
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible
