---
- name: Prepare
  hosts: all
  tasks:
    - name: Make a dummy swap fstab entry
      become: true
      ansible.builtin.lineinfile:
        path: /etc/fstab
        state: present
        line: '/opt/swap none swap defaults 0 0'
        mode: '0644'
        create: true
