---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vault_verify_version: v1.12.0
    vault_verify_hash: 558abfa75702b5dab4c98e86b802fb9aef43b0eb
  tasks:
    - name: Verify the Vault status
      ansible.builtin.include_tasks: ../common/verify.yml
