---
- name: Verify
  hosts: all
  vars:
    vault_hsm_token_label: "vault-hsm-key"
  tasks:
    - name: Get {{ vault_hsm_token_label }} slot
      ansible.builtin.shell:
        cmd: >-
          softhsm2-util --show-slots | grep -B15 {{ vault_hsm_token_label }} |
          grep ^Slot | sed 'q;d' | cut -d\  -f2
      changed_when: false
      register: hsm_vault_slot

    - name: Set the slot fact for Vault HSM
      ansible.builtin.set_fact:
        vault_hsm_token_slot: "{{ hsm_vault_slot.stdout }}"
        cacheable: true

    - name: Test generating an RSA2048 key in Slot {{ vault_hsm_token_slot }}
      ansible.builtin.shell:
        cmd: >-
          pkcs11-tool --modul /usr/lib64/libsofthsm2.so --login --login-type user
          --pin 1234 --keypairgen --id 736f6d652d6964 --key-type rsa:2048 --slot {{ vault_hsm_token_slot }}
      register: pkcs11_keygen
      changed_when: true
      failed_when: pkcs11_keygen.rc != 0
