---
- name: Converge
  hosts: all
  vars:
    vault_autounseal_recovery_key_print: true
    vault_version: vault-enterprise-hsm-1.12.1+ent-1
    vault_user: vault
    vault_group: vault
    vault_hsm_pin: "1234"
    vault_log_level: DEBUG
    vault_softhsm_log_level: DEBUG
    vault_raft_members:
      - ip: "{{ hostvars['vault-hsm']['ansible_default_ipv4']['address'] }}"
        port: 8200
  tasks:
    - name: "Install vault"
      ansible.builtin.include_role:
        name: "install_vault"
    - name: "Include softhsm"
      ansible.builtin.include_role:
        name: "vault_softhsm"
    - name: "Include autounseal_vault"
      ansible.builtin.include_role:
        name: "autounseal_vault_hsm"
