---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: redhat8-vault-hsm
    image: almalinux:8
    command: /sbin/init
    privileged: true
    capabilities:
      - CAP_SYS_ADMIN
      - CAP_IPC_LOCK
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible
