---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7-hsm
    image: quay.io/centos/centos:centos7
    pre_build_image: true
  - name: almalinux8-hsm
    image: almalinux:8
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/converge.yml
verifier:
  name: ansible
