---
- name: Verify
  hosts: all
  vars:
    fact_vault_hsm_slot: "0"
    vault_hsm_token_label: vault-hsm-key
  tasks:
    - name: Fail if {{ vault_hsm_token_label }} is not in Slot {{ fact_vault_hsm_slot }}
      ansible.builtin.shell:
        cmd: >-
          softhsm2-util --show-slots | grep -B15 {{ vault_hsm_token_label }} |
          grep ^Slot | sed 'q;d' | cut -d\  -f2
      register: hsm_vault_slot
      changed_when: false
      failed_when: hsm_vault_slot.stdout != fact_vault_hsm_slot

    - name: Test generating an RSA2048 key in the {{ fact_vault_hsm_slot }}
      ansible.builtin.shell:
        cmd: >-
          pkcs11-tool --module {{ vault_hsm_lib_path }} --login --login-type user
          --pin 1234 --keypairgen --id 736f6d652d6964 --key-type rsa:2048
      register: pkcs11_keygen
      changed_when: true
      failed_when: pkcs11_keygen.rc != 0
