---
- name: Check if we can successfully generate a softhsm RSA2048key
  hosts: all
  vars:
    vault_hsm_token_label: vault-hsm-key
    vault_hsm_lib_path: "/usr/lib64/libsofthsm2.so"
  tasks:
    - name: Get {{ vault_hsm_token_label }} slot
      ansible.builtin.shell:
        cmd: >-
          softhsm2-util --show-slots | grep -B15 {{ vault_hsm_token_label }} |
          grep ^Slot | sed 'q;d' | cut -d\  -f2
      changed_when: false
      register: hsm_vault_slot

    - name: Test generating an RSA2048 key
      ansible.builtin.shell:
        cmd: >-
          pkcs11-tool --module {{ vault_hsm_lib_path }} --login --login-type user
          --pin 1234 --keypairgen --id 736f6d652d6964 --key-type rsa:2048
      register: pkcs11_keygen
      changed_when: true
      failed_when: pkcs11_keygen.rc != 0
